{"name": "Попытка изменения данных залогиненного пользователя c другой почтой: статус-код 401, тело ответа соответствует документации", "status": "passed", "start": 1719213962924, "stop": 1719213963788, "uuid": "83212e3e-e46d-47ee-a912-d474fc7ba17f", "historyId": "6d07b61fa3b31a368aac465052ec4d4b", "testCaseId": "6d07b61fa3b31a368aac465052ec4d4b", "fullName": "tests.test_update_user.TestUpdateUser#test_update_user_data_with_exist_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "DESKTOP-RJ2RHPG"}, {"name": "thread", "value": "6948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user"}]}